### ISSUE TITLE
feat: Data Gatherers

### ISSUE THREAD

**Issue by Dhravya** [cake-cutter/cakecutter#14]
Data gatherers are kinda like questions but they are not asked. They are commands which runs to gather data. like suppose you wanted to get the user's git username you can run git config --get user.name :-

```toml
[gatherers]
id-of-gatherer = "git config --get user.name"
```
Before creating the template these commands will be run and there output will be saved. and u can use them just like questions
